// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Author      pgtype.Text        `json:"author"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	Content     pgtype.Text        `json:"content"`
	Url         pgtype.Text        `json:"url"`
	UserID      string             `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
