// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteBook(ctx context.Context, arg DeleteBookParams) error
	GetBook(ctx context.Context, arg GetBookParams) (Book, error)
	GetBooksByUser(ctx context.Context, userID string) ([]Book, error)
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
